In [ ]:
import pandas as pd
import pandas

In [ ]:
# 깃허브의 www.github.com/hyowakn -> python_lec
csFilePath = "https://raw.githubusercontent.com/hyokwan/python-lecture/refs/heads/master/dataset/kopo_customerdata.csv"
customerData = pandas.read_csv(csFilePath)
customerData

,CUSTOMERCODE,STATENAME,ST,GENDER,DOB,GENDER1,EMAIL,FEST_CNT,TOTAL_AMOUNT,AC_AMOUNT,AV_AMOUNT,HA_AMOUNT,EMI_CE_AMOUNT,IS_HIGHEND,CNT_VIST,GAP_VISIT
0,1503989,State2,2,Male,0,1,1,0,30300,0,30300,0,0,0,1,0
1,1190338,State2,2,Male,0,1,0,1,46500,0,46500,0,0,0,1,0
2,1424715,State2,2,Female,0,2,0,0,22700,0,0,22700,0,0,1,0
3,2483305,State2,2,Male,0,1,0,1,31400,0,31400,0,0,0,1,0
4,1178802,State2,2,Male,0,1,0,1,44900,0,0,44900,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299995,465757,State1,1,Male,0,1,0,0,40600,0,40600,0,0,0,1,0
299996,1890264,State1,1,Male,0,1,0,1,48000,48000,0,0,0,0,1,0
299997,1857537,State1,1,Female,0,2,0,0,32300,0,0,32300,0,0,1,0
299998,2209324,State1,1,Male,0,1,0,1,48500,0,48500,0,0,0,1,0
299999,1875146,State1,1,Male,0,1,0,1,16500,0,0,16500,0,0,1,0

In [ ]:
# customerData에서 TOTAL_AMOUNT를 리스트로 뽑아내서 customerTotalLost라는 변수에 넣음
customerTotalLost = list( customerData.TOTAL_AMOUNT )
customerTotalLost

# customerTotalLost에서 min과 max로 최소값과 최대값을 추출 하고 각각 min_customer_data와 max_customer_data라는 변수에 넣음
min_customer_data= min(customerTotalLost)
max_customer_data= max(customerTotalLost)

# min_customer_data와 max_customer_data를 리스트화 하여 각각 min_except와 max_except라는 변수에 넣어줌
min_except = [min_customer_data]
max_except = [max_customer_data]

# customerTotalLost에서 min_except의 값과 max_except값을 제거해줌
customerTotalLost.remove(min_except[0])
customerTotalLost.remove(max_except[0])

# customerTotalLost의 합과 리스트 내부 요소의 길이(갯수)를 구해 sum_customer_data와 len_customer_data라는 변수에 넣어줌
sum_customer_data = sum(customerTotalLost)
len_customer_data = len(customerTotalLost)

# sum_customer_data와 len_customer_data로 평균을 내고 int함수를 이용해 정수로 바꾼뒤 result변수에 넣어줌
average = sum_customer_data / len_customer_data
result = int(average)

result

35218